### ISSUE TITLE
"None" appears CitySpeciality Case

### ISSUE THREAD

**Issue by jlrJames** [rlofc/hexroll#6]
https://pendicepaper.com/hexroll/vault/cf46f1cf/#71153c37

In City of Karaja: "The city is also known for its fine None shops" 

Presumably because in lines 179-192 of settlement.yaml somehow neither if case is getting caught.

**Comment by rlofc** [comment]
Nice find. Thanks!

**Comment by rlofc** [comment]
Fixed in 3ecb100
